[fix] init-laravel script - Check for .env file existence, run composer install

diff --git a/.docker/scripts/init-laravel b/.docker/scripts/init-laravel
--- a/.docker/scripts/init-laravel
+++ b/.docker/scripts/init-laravel
@@ -3,6 +3,23 @@ source .env
 
 # Laravel .env file
 TARGET_ENV="${APP_SRC}/.env"
+# Laravel .env.example file
+TARGET_ENV_EXAMPLE="${APP_SRC}/.env.example"
+
+if [ ! -f ${TARGET_ENV} ] ; then
+  # No .env file found. Try to copy it from .env.example
+  echo -e "\nNo ${TARGET_ENV} file found. Trying to copy from ${TARGET_ENV_EXAMPLE}..."
+  cp -f ${TARGET_ENV_EXAMPLE} ${TARGET_ENV} 2>/dev/null
+
+  if [ ! -f ${TARGET_ENV} ] ; then
+    # Still no .env file
+    echo -e "\nERROR: there is no ${TARGET_ENV} file."
+    echo -e "Please create one manually, then run this script again.\n"
+    exit 1
+  fi
+fi
+
+echo "File ${TARGET_ENV} found. Performing variable replacing..."
 
 # Read options from main .env file and write
 # them into Laravel .env file
@@ -21,6 +38,9 @@ ENV_FILE=$(sed "s/MAIL_HOST=.*/MAIL_HOST=mailhog/" <<< "${ENV_FILE}")
 ENV_FILE=$(sed "s/MAIL_PORT=.*/MAIL_PORT=1025/" <<< "${ENV_FILE}")
 ENV_FILE=$(sed "s/APP_URL=.*/APP_URL=\"http:\/\/${APP_HOST}\"/" <<< "${ENV_FILE}")
 echo "${ENV_FILE}" > ${TARGET_ENV}
+
+# Before calling artisan commands, ensure composer dependencies have been installed.
+.docker/scripts/composer install
 
 .docker/scripts/artisan config:clear
 .docker/scripts/artisan config:cache
